version: 2

models:
  - name: stg_orders
    columns:
      - name: ORDER_ID
        tests: [not_null, unique]
      - name: CUSTOMER_ID
        tests:
          - not_null
          - relationships:
              to: source('raw', 'customers')
              field: CUSTOMER_ID
      - name: ORDER_STATUS
        tests:
          - accepted_values:
              values: ['PLACED', 'SHIPPED', 'DELIVERED', 'CANCELLED']
      - name: TOTAL_AMOUNT
        tests:
          - non_negative
